### ISSUE TITLE
Classes in Java artifact do not match the protos shipped with it

### ISSUE THREAD

**Issue by thesamet** [googleapis/api-common-protos#83]
In the 2.0.1 jar, `google/api/endpoint.proto` contains a `repeated string features = 4`, however the corresponding Java class file doesn't have any of the methods corresponding to this field.

**Comment by miraleung** [comment]
Closing because the Bazel build doesn't have relevant rules. Please feel free to reopen the Java build definition is root-caused back to this repo.

**Comment by thesamet** [comment]
@miraleung 
I am not sure why this issue was closed. The Java classes that are shipped with the jar artifact do not match the protos that are shipped within the same jar. This is also occurring with 2.1.0. I am not sure what you meant by "Please feel free to reopen the Java build definition is root-caused back to this repo." - is there an upstream ticket that need to be filed?

**Comment by thesamet** [comment]
@miraleung what is the next step for this issue resolved? I don't have a re-open button on this issue.

**Comment by miraleung** [comment]
The Bazel build definitions in this repo all pertain to `proto_package`, so there doesn't seem to be any build definition that produces a Java artifact. If you find one though, please link it here. Otherwise, the discrepancy is either due to an upstream issue in the protobuf compiler or something downstream that packages the protos into a jar.

Note that this repo is as actively maintained as [googleapis](github.com/googleapis/googleapis), which contains a superset of all these protos, so consider using that instead.

**Comment by thesamet** [comment]
Ack, thanks for clarifying the maven jar is published elsewhere. Filed https://github.com/googleapis/java-common-protos/issues/134
