### ISSUE TITLE
How often is this repository synced with googleapis?

### ISSUE THREAD

**Issue by johanbrandhorst** [googleapis/api-common-protos#88]
I had a quick look at a few protobuf files from googleapis and it seems like this repository is not being kept up-to-date with the changes made to protobuf files within googleapis. Is this repository still being migrated to, as detailed in https://github.com/googleapis/go-genproto/issues/92#issuecomment-413901416?

**Comment by noahdietz** [comment]
This repository is not actively synced. It occasionally gets spot updates for some dependent packages. No it is not being migrated to, go-genproto continues to be generated based on protos from github.com/googleapis/googleapis.  That repo is the most up-to-date project and should be used instead.

I will close this now, but if there is anything else, please feel free to comment.

**Comment by johanbrandhorst** [comment]
May be worth putting in the README that this repository is deprecated then?

**Comment by timburks** [comment]
I'd also like to see the state of this repo clarified. Browsing the googleapis collection, it's not immediately clear which directories are common protos (and suggested for reuse) and which are APIs. People with inside knowledge might use the presence of service config to identify APIs (or something else), but this repo provided helpful clarity on what's available for reuse.

If this repo is a subset of googleapis, and if googleapis remains authoritative and available, would it be helpful to have an update script that pulls new types and updates from the googleapis repo so that this could be updated by external contributors? I'd be happy to draft a PR with that.

**Comment by jankrynauw** [comment]
Comparing for example the `option go_package` entries in the `color.proto` files:
- [api-common-protos](https://github.com/googleapis/api-common-protos/blob/main/google/type/color.proto)
- [googleapis](https://github.com/googleapis/googleapis/blob/master/google/type/color.proto)

both have the exact same `option go_package` entry of: 
`option go_package = "google.golang.org/genproto/googleapis/type/color;color";`

Yet looking at the generated protobufs behind these `go_package` entries, they seem to reflect the official `googleapis` definitions.  For example, the [protobuf](https://github.com/googleapis/go-genproto/blob/main/googleapis/type/phone_number/phone_number.pb.go) for `phone_number.proto` is available in the go library but nowhere defined in this (`api-common-proto`) repository.

For `go` packages at least, the golden source of protobufs referred to in this repo definitions, is not driven by this repo, but instead driven by the `googleapis` repo, There is therefore a real danger of inconsistent definitions between proto definitions in this library and the underlying `go` packages imported.

**Comment by parthea** [comment]
I'm going to close this issue as obsolete as it is recommended to use the [googleapis](https://github.com/googleapis/googleapis) repo instead.

**Comment by johanbrandhorst** [comment]
> May be worth putting in the README that this repository is deprecated then?

Has this been done yet?
